### PR TITLE
Add TG icon

### PR DESCRIPTION
**Pull request by hlaposhka**

### CODE REVIEW

**Comment by IanMayo** [comment]
@hlaposhka  - I now realise how the icons are created.
It's a white SVG over a filled rectangle of the required color. The corners of the rectangle are rounded to give the circular icon.

You can see how it is done by `inspecting` an icon on this map:
https://serge-review.herokuapp.com/storybook/?path=/story/local-mapping--default

So, I think we just need the "TG" letters in the right size, in white.

I've attached a sample SVG file with the correct (white) styling.

[merchant-vessel.svg.zip](https://github.com/debrief/debrief-icons/files/6304776/merchant-vessel.svg.zip)

Thanks!

**Comment by hlaposhka** [comment]
@IanMayo I'm glad that we figured it out, I just remember how I created these icons and that initially, they went without a circle, this raised doubts)

I updated the color and deleted the extraversion with a circle

**Comment by IanMayo** [comment]
@hlaposhka  - new icon working perfectly:
image

**Comment by hlaposhka** [comment]
@IanMayo - excellent!

**Pull request merged**
