### PR TITLE
Added new 24 NATO icons

### LINKED ISSUE #89: New set of SVG icons, please
image

Images here: [unit_symbols.zip](https://github.com/debrief/debrief-icons/files/9939968/unit_symbols.zip)

We have a requirement for a new set of symbols, please.

They are to be in SVG, but will take a color - the same as the existing symbols in this folder: 
* https://github.com/debrief/debrief-icons/tree/master/counters/red_blue

The icons should keep their filename, but with `.png` changed to `svg`.

I'd like them to go into a new folder titled `counters/nato`, please.

The icons do not have to be exact reproductions, you are welcome to make steps to improve the readability if you wish.  I see the _Trident_ shape in `land_blue_ssm.png` could be a little larger.

### PR DESCRIPTION
**Pull request by hlaposhka**
Fixes #89 

Created a new set of 24 NATO icons
NATO set

### CODE REVIEW

**Comment by IanMayo** [comment]
@hlaposhka - I've just compared the screenshot with the originals I was provided with.  Significantly, the lines should be black, not white.

A couple more items:
- could you make the vertical "stick" on `blue_hq` a little longer?  I accept that this will probably make the blue rectangle a little smaller
- the "stick" on `red_hq` also needs to be longer too, please
- there is still some more file renaming to do, please (putting the force at the start).  But, I'm happy to do this, if you don't want to.

**Comment by hlaposhka** [comment]
About changes: 
- I made a white outline to make the icons more consistent with others in the project.  I read that this is acceptable with a dark background.  But I will change it to black.
- For "red_hq" and "blue-hq" I can move the objects higher on the canvas, I thought to do this, but then the center of the shape and the canvas will not match.  Or I can reduce the size of the shape itself, then the center will match.
- Okay, I will change naming

**Comment by IanMayo** [comment]
Hello :=)
> * I made a white outline to make the icons more consistent with others in the project.  I read that this is acceptable with a dark background.  But I will change it to black.

For this game, the players will only see this set of icons - s0 they don't have to be consistent with previous ones.

> * For "red_hq" and "blue-hq" I can move the objects higher on the canvas, I thought to do this, but then the center of the shape and the canvas will not match.  Or I can reduce the size of the shape itself, then the center will match.

Aah, yes - I see.  I think we'll have to take the approach that the `HQ` is located at the centre of the whole symbol, not the centre of the rectangle.

> * Okay, I will change naming

Thanks !

**Comment by hlaposhka** [comment]
Hello,

The blue color has issues with the black stroke. This makes the icons unreadable. I can change the shade of blue to lighter or make the icon inside white
Screenshot 2022-11-08 at 20 24 33

**Comment by IanMayo** [comment]
Aah, I see what has happened :-)

You have adopted the Blue/Red shades that we have used in the past.  For this set of icons,  they want the blue/red shades they provided in their screenshot, please:
image

**Comment by hlaposhka** [comment]
New look with updated color scheme

NATOset__new-color

**Review by IanMayo — APPROVED** [review]
Perfect!

**Pull request merged**
